package com.itany.nmms.dao;

import com.itany.nmms.entity.Product;
import com.itany.nmms.entity.ProductExample;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_product
     *
     * @mbggenerated Sat Apr 20 15:58:09 CST 2024
     */
    int countByExample(ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_product
     *
     * @mbggenerated Sat Apr 20 15:58:09 CST 2024
     */
    int deleteByExample(ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_product
     *
     * @mbggenerated Sat Apr 20 15:58:09 CST 2024
     */
    int deleteByNo(String productNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_product
     *
     * @mbggenerated Sat Apr 20 15:58:09 CST 2024
     */
    int insert(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_product
     *
     * @mbggenerated Sat Apr 20 15:58:09 CST 2024
     */
    int insertSelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_product
     *
     * @mbggenerated Sat Apr 20 15:58:09 CST 2024
     */
    List<Product> selectByExample(ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_product
     *
     * @mbggenerated Sat Apr 20 15:58:09 CST 2024
     */
    Product selectByNo(String productNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_product
     *
     * @mbggenerated Sat Apr 20 15:58:09 CST 2024
     */
    int updateByExampleSelective(@Param("record") Product record, @Param("example") ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_product
     *
     * @mbggenerated Sat Apr 20 15:58:09 CST 2024
     */
    int updateByExample(@Param("record") Product record, @Param("example") ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_product
     *
     * @mbggenerated Sat Apr 20 15:58:09 CST 2024
     */
    int updateByPrimaryKeySelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_product
     *
     * @mbggenerated Sat Apr 20 15:58:09 CST 2024
     */
    int updateByPrimaryKey(Product record);

    List<Product> selectProductsWithType(ProductExample productExample);
}