package com.itany.nmms.dao;

import com.itany.nmms.entity.Sequence;
import com.itany.nmms.entity.SequenceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SequenceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_sequence
     *
     * @mbggenerated Sat Apr 13 16:02:31 CST 2024
     */
    int countByExample(SequenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_sequence
     *
     * @mbggenerated Sat Apr 13 16:02:31 CST 2024
     */
    int deleteByExample(SequenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_sequence
     *
     * @mbggenerated Sat Apr 13 16:02:31 CST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_sequence
     *
     * @mbggenerated Sat Apr 13 16:02:31 CST 2024
     */
    int insert(Sequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_sequence
     *
     * @mbggenerated Sat Apr 13 16:02:31 CST 2024
     */
    int insertSelective(Sequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_sequence
     *
     * @mbggenerated Sat Apr 13 16:02:31 CST 2024
     */
    List<Sequence> selectByExample(SequenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_sequence
     *
     * @mbggenerated Sat Apr 13 16:02:31 CST 2024
     */
    Sequence selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_sequence
     *
     * @mbggenerated Sat Apr 13 16:02:31 CST 2024
     */
    int updateByExampleSelective(@Param("record") Sequence record, @Param("example") SequenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_sequence
     *
     * @mbggenerated Sat Apr 13 16:02:31 CST 2024
     */
    int updateByExample(@Param("record") Sequence record, @Param("example") SequenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_sequence
     *
     * @mbggenerated Sat Apr 13 16:02:31 CST 2024
     */
    int updateByPrimaryKeySelective(Sequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_sequence
     *
     * @mbggenerated Sat Apr 13 16:02:31 CST 2024
     */
    int updateByPrimaryKey(Sequence record);
}